# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bertvv/centos72"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end

  # network fix for vagrant 1.9.1
  config.vm.provision "shell", run: "always", inline: "systemctl restart network"

  builder_setup = <<-BUILDER_SETUP
    yum install java -y
    yum install docker -y
    systemctl enable docker
    systemctl start docker
    cp -r /vagrant/certs /home/vagrant/
    mkdir --parent /etc/docker/certs.d/192.168.33.10:5000
    cp /vagrant/certs/domain.crt /etc/docker/certs.d/192.168.33.10:5000/ca.crt    
    docker pull jenkins
    docker pull registry
    docker pull sonatype/nexus
    docker pull tomcat
    docker network create user-network
    mkdir --mode a+w /home/vagrant/jenkins_home
    mkdir --mode a+w /home/vagrant/nexus_work
    mkdir --mode a+w /home/vagrant/registry_data
    docker run --detach --name jenkins  --restart always --network user-network --publish 8080:8080 --volume /home/vagrant/jenkins_home:/var/jenkins_home:z jenkins
    docker run --detach --name nexus    --restart always --network user-network --publish 8081:8081 --volume /home/vagrant/nexus_work:/sonatype-work:z --env MAX_HEAP=256m sonatype/nexus
    docker run --detach --name registry --restart always --network user-network --publish 5000:5000 --volume /home/vagrant/registry_data:/var/lib/registry:z \
      --volume /vagrant/certs:/certs:z \
      --env REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
      --env REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
      registry
    yum install bridge-utils
  BUILDER_SETUP

  config.vm.define "builder" do |builder|
    builder.vm.hostname = "builder"
    builder.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "builder"
      virtualbox.memory = 2048
    end
    builder.vm.network "private_network", ip: "192.168.33.10"
    builder.vm.network "forwarded_port", guest: 80, host: 8080
    builder.vm.network "forwarded_port", guest: 8080, host: 8082
    builder.vm.network "forwarded_port", guest: 8081, host: 8084
    builder.vm.provision "shell", inline: builder_setup
  end

  tester_setup = <<-TESTER_SETUP
    yum install java -y
    yum install docker -y
    mkdir --parent /etc/docker/certs.d/192.168.33.10:5000
    cp /vagrant/certs/domain.crt /etc/docker/certs.d/192.168.33.10:5000/ca.crt
    systemctl enable docker
    systemctl start docker
  TESTER_SETUP

  config.vm.define "tester" do |tester|
    tester.vm.hostname = "tester"
    tester.vm.provider "virtualbox" do |virtualbox|
      virtualbox.name = "tester"
      virtualbox.memory = 256
    end
    tester.vm.network "private_network", ip: "192.168.33.11"
    tester.vm.provision "shell", inline: tester_setup
  end

end
