# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bertvv/centos72"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end

  config.vm.define "machine1" do |machine1|
    machine1.vm.hostname = "machine1"
    machine1.vm.provision "shell", inline: <<-INSTALL_SHELL
      yum install git -y
    INSTALL_SHELL
    machine1.vm.provision "shell", privileged: false, inline: <<-CLONE_GIT
      git clone https://github.com/JugosD/DevOpsTraining.git
      git checkout task1
    CLONE_GIT
  end

  config.vm.define "machine2" do |machine2|
    machine2.vm.hostname = "machine2"
  end

end
